<?php

require_once __DIR__ . "/../../models/User.php";

use lore\persistence\Query;
use lore\mvc\ViewController;

class UserController extends ViewController
{

    /**
     * @var \lore\persistence\Query
     */
    private $userQuery;

    public function createNewModelInstance()
    {
        $this->userQuery = \lore\Lore::app()->getPersistence()->getRepository("todo/mysql")->query(User::class);
        return new User();
    }

    protected function emailExists(){
        return $this->userQuery->where("email")->equals($this->getModel()->getEmail())->exists();
    }

    /**
     * @return User
     */
    public function getModel(): \lore\mvc\Model
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

    /**
     * @uri /form
     * @method get
     */
    public function form(){
        $this->render("user/registerForm.php");
    }

    /**
     * @uri /register
     * @method post
     */
    public function register(){
        if($this->loadAndValidateModel() && !$this->emailExists()){
            $this->getModel()->insert();
            $this->redirect("");
        }else{
            $this->putModelInResponse();
            $this->putErrorsInResponse();
            $this->render("user/registerForm.php");
        }
    }

}