<?php
use lore\mvc\ViewController;

require_once __DIR__ . "/../../models/User.php";
require_once __DIR__ . "/../../dao/UserDAO.php";

/**
 * Created by PhpStorm.
 * User: Felipe Oliveira
 * Date: 12/08/2017
 * Time: 10:36
 */
class UserController extends ViewController
{
    /**
     * @var UserDAO
     */
    private $dao;

    public function createNewModelInstance()
    {
        $this->dao = new UserDAO();
        return new User();
    }

    /**
     * @return \User
     */
    public function getModel(): \lore\mvc\Model
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

    /**
     * @uri /save
     * @method post
     */
    public function save()
    {
        if ($this->loadAndValidateModel()) {
            if ($this->getModel()->getId() == null) {
                $this->dao->insert($this->getModel());
                \lore\web\Session::put("user", $this->getModel()->serializeToSession());
                $this->redirect("");
            }else{
                die("Not integrated yet!");
            }
        }else{
            $this->putModelInResponse();
            $this->render("user/form.php");
        }
    }
}